create table if not exists public.reservations (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  phone_key text not null,
  email text not null default '',
  reservation_date date not null,
  reservation_time text not null,
  guests integer not null check (guests > 0),
  notes text,
  status text not null default 'pending' check (status in ('pending', 'confirmed', 'cancelled')),
  notification_status text not null default 'not_sent',
  arrived boolean not null default false,
  arrival_previous_status text,
  booking_source text not null default 'website' check (booking_source in ('website', 'manual')),
  created_at timestamptz not null default now()
);

create unique index if not exists reservations_phone_day_unique
  on public.reservations (phone_key, reservation_date);

create index if not exists reservations_date_time_idx
  on public.reservations (reservation_date desc, reservation_time desc);

create table if not exists public.email_verifications (
  id bigint generated by default as identity primary key,
  email text not null,
  code text not null,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists email_verifications_lookup_idx
  on public.email_verifications (email, code, expires_at desc);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  date date not null,
  day text not null,
  month text not null,
  title text not null,
  music text not null,
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists events_date_order_idx
  on public.events (date asc, display_order asc);

create table if not exists public.cocktail_cards (
  id bigint generated by default as identity primary key,
  image text not null,
  alt text,
  eyebrow text not null,
  title text not null,
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.cocktail_cards (image, alt, eyebrow, title, display_order)
values
  ('/assets/cartel/ecobar.jpg', 'Cartel cocktail being poured at the bar', 'Signature Pour', 'Escobar serve', 0),
  ('/assets/cartel/muchroom.jpeg', 'Cartel mushroom cocktail with rosemary garnish', 'Forest Ritual', 'Mushroom cocktail', 1),
  ('/assets/cartel/doctor.jpg', 'Cartel doctor cocktail served with a drip presentation', 'Doctor''s Order', 'Drip therapy serve', 2)
on conflict do nothing;

insert into public.events (date, day, month, title, music, display_order)
values
  ('2026-05-29', '29', 'May', 'DJ MG', 'Old School R&B Music', 0),
  ('2026-05-30', '30', 'May', 'DJ Rafaelos', 'Mainstream Music', 1),
  ('2026-05-31', '31', 'May', 'DJ Chris NI', 'Mainstream Music', 2)
on conflict do nothing;

alter table public.reservations enable row level security;
alter table public.email_verifications enable row level security;
alter table public.events enable row level security;
alter table public.cocktail_cards enable row level security;
